/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id: process.env.NEXT_PUBLIC_AWS_COGNITO_POOL_ID,
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_ExBpU4w5a",
  aws_user_pools_web_client_id: process.env.NEXT_PUBLIC_AWS_USER_POOL_CLIENT_ID,
  oauth: {},
  aws_cognito_login_mechanism: ["EMAIL"],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_appsync_graphqlEndpoint:
    process.env.NEXT_PUBLIC_AWS_APPSYNC_GRAPHQLENDPOINT,
  aws_appsync_region: "us-east-1",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
};

export default awsmobile;
